apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: ashishtkumar/aws-eks
    # github.com/project-slug: ashishtkumar/${{ values.name }}
    github.com/workflows: manage-eks-cluster.yml
    terraform.io/workspace: backstage-eks-aws
    terraform.io/organization: srepro
  description: ${{ values.name }} running on AWS EKS cluster managed by Terraform
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
